# Data Cleaning - Student Mental Health Dataset

## Objective
This notebook performs data cleaning and preprocessing on the raw student mental health dataset. The goal is to produce a clean, consistent dataset suitable for exploratory data analysis (EDA), feature engineering, model training, and the wellness score engine.

### Cleaning Objectives
- Inspect dataset structure
- Identify missing values and duplicates
- Remove irrelevant features
- Correct invalid values
- Standardize data
- Export cleaned dataset

# Data Cleaning

This notebook performs the initial inspection and cleaning of the Kaggle Student Depression dataset.

Steps:
1. Load dataset
2. Inspect data
3. Handle missing values
4. Remove duplicates
5. Standardize categorical variables
6. Save cleaned dataset

In [76]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [77]:
df = pd.read_excel(r"D:\Project\Mental-Health-Analyzer-New\ml\data\raw\students_dataset.xlsx")
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5,0,8.97,2,0,'5-6 hours',Healthy,B.Pharm,Yes,3,1,No,1
1,8,Female,24,Bangalore,Student,2,0,5.90,5,0,'5-6 hours',Moderate,BSc,No,3,2,Yes,0
2,26,Male,31,Srinagar,Student,3,0,7.03,5,0,'Less than 5 hours',Healthy,BA,No,9,1,Yes,0
3,30,Female,28,Varanasi,Student,3,0,5.59,2,0,'7-8 hours',Moderate,BCA,Yes,4,5,Yes,1
4,32,Female,25,Jaipur,Student,4,0,8.13,3,0,'5-6 hours',Moderate,M.Tech,Yes,1,1,No,0

In [78]:
df.shape

(27901, 18)

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  int64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  int64
 6   Work Pressure                          27901 non-null  int64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  int64
 9   Job Satisfaction                       27901 non-null  int64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  int64
 15  Financial Stress                       27901 non-null  object
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(1), int64(8), object(2), str(7)
memory usage: 3.8+ MB

In [80]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [81]:
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

1. id
2. Gender
3. Age
4. City
5. Profession
6. Academic Pressure
7. Work Pressure
8. CGPA
9. Study Satisfaction
10. Job Satisfaction
11. Sleep Duration
12. Dietary Habits
13. Degree
14. Have you ever had suicidal thoughts ?
15. Work/Study Hours
16. Financial Stress
17. Family History of Mental Illness
18. Depression

In [82]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,27901.0,70442.149421,40641.175216,2.0,35039.00,70684.00,105818.00,140699.0
Age,27901.0,25.822300,4.905687,18.0,21.00,25.00,30.00,59.0
Academic Pressure,27901.0,3.141214,1.381465,0.0,2.00,3.00,4.00,5.0
Work Pressure,27901.0,0.000430,0.043992,0.0,0.00,0.00,0.00,5.0
CGPA,27901.0,7.656104,1.470707,0.0,6.29,7.77,8.92,10.0
Study Satisfaction,27901.0,2.943837,1.361148,0.0,2.00,3.00,4.00,5.0
Job Satisfaction,27901.0,0.000681,0.044394,0.0,0.00,0.00,0.00,4.0
Work/Study Hours,27901.0,7.156984,3.707642,0.0,4.00,8.00,10.00,12.0
Depression,27901.0,0.585499,0.492645,0.0,0.00,1.00,1.00,1.0

In [83]:
df.describe(include="object").T

,count,unique,top,freq
Gender,27901,2,Male,15547
City,27901,52,Kalyan,1570
Profession,27901,14,Student,27870
Sleep Duration,27901,5,'Less than 5 hours',8310
Dietary Habits,27901,4,Unhealthy,10317
Degree,27901,28,'Class 12',6080
Have you ever had suicidal thoughts ?,27901,2,Yes,17656
Financial Stress,27901,6,5,6715
Family History of Mental Illness,27901,2,No,14398

Handling Missing Values and Duplicate rows

In [84]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing[missing["Missing Count"]>0]

missing.sort_values("Percentage", ascending=False)

Empty DataFrame
Columns: [Missing Count, Percentage]
Index: []

In [85]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [86]:
for column in df.columns:
    
    print("="*70)
    print(column)
    print("-"*70)
    
    print(df[column].value_counts(dropna=False))
    print()

======================================================================
id
----------------------------------------------------------------------
id
2         1
8         1
26        1
30        1
32        1
         ..
140685    1
140686    1
140689    1
140690    1
140699    1
Name: count, Length: 27901, dtype: int64

======================================================================
Gender
----------------------------------------------------------------------
Gender
Male      15547
Female    12354
Name: count, dtype: int64

======================================================================
Age
----------------------------------------------------------------------
Age
24    2258
20    2237
28    2133
29    1950
33    1893
25    1784
21    1726
23    1645
18    1587
19    1560
34    1468
27    1462
31    1427
32    1262
22    1160
26    1155
30    1145
35      10
38       8
36       7
42       4
39       3
48       3
43       2
46       2
37       2
58       1
49       1
51       1
44       1
59       1
54       1
56       1
41       1
Name: count, dtype: int64

======================================================================
City
----------------------------------------------------------------------
City
Kalyan                  1570
Srinagar                1372
Hyderabad               1340
Vasai-Virar             1290
Lucknow                 1155
Thane                   1139
Ludhiana                1111
Agra                    1094
Surat                   1078
Kolkata                 1066
Jaipur                  1036
Patna                   1007
Visakhapatnam            969
Pune                     968
Ahmedabad                951
Bhopal                   934
Chennai                  885
Meerut                   825
Rajkot                   816
Delhi                    768
Bangalore                767
Ghaziabad                745
Mumbai                   699
Vadodara                 694
Varanasi                 685
Nagpur                   651
Indore                   643
Kanpur                   609
Nashik                   547
Faridabad                461
Saanvi                     2
Bhavna                     2
City                       2
Harsha                     2
M.Tech                     1
'Less Delhi'               1
3                          1
'Less than 5 Kalyan'       1
Mira                       1
Vaanya                     1
Gaurav                     1
Harsh                      1
Reyansh                    1
Kibara                     1
Rashi                      1
ME                         1
M.Com                      1
Nalyan                     1
Mihir                      1
Nalini                     1
Nandini                    1
Khaziabad                  1
Name: count, dtype: int64

======================================================================
Profession
----------------------------------------------------------------------
Profession
Student                     27870
Architect                       8
Teacher                         6
'Digital Marketer'              3
'Content Writer'                2
Chef                            2
Doctor                          2
Pharmacist                      2
'Civil Engineer'                1
'UX/UI Designer'                1
'Educational Consultant'        1
Manager                         1
Lawyer                          1
Entrepreneur                    1
Name: count, dtype: int64

======================================================================
Academic Pressure
----------------------------------------------------------------------
Academic Pressure
3    7462
5    6296
4    5155
1    4801
2    4178
0       9
Name: count, dtype: int64

======================================================================
Work Pressure
----------------------------------------------------------------------
Work Pressure
0    27898
5        2
2        1
Name: count, dtype: int64

======================================================================
CGPA
----------------------------------------------------------------------
CGPA
8.0400    821
9.9600    425
5.7400    410
8.9500    371
9.2100    343
         ...
6.6400      1
7.0625      1
6.9800      1
6.4400      1
6.0900      1
Name: count, Length: 332, dtype: int64

======================================================================
Study Satisfaction
----------------------------------------------------------------------
Study Satisfaction
4    6359
2    5838
3    5821
1    5451
5    4422
0      10
Name: count, dtype: int64

======================================================================
Job Satisfaction
----------------------------------------------------------------------
Job Satisfaction
0    27893
2        3
4        2
1        2
3        1
Name: count, dtype: int64

======================================================================
Sleep Duration
----------------------------------------------------------------------
Sleep Duration
'Less than 5 hours'    8310
'7-8 hours'            7346
'5-6 hours'            6183
'More than 8 hours'    6044
Others                   18
Name: count, dtype: int64

======================================================================
Dietary Habits
----------------------------------------------------------------------
Dietary Habits
Unhealthy    10317
Moderate      9921
Healthy       7651
Others          12
Name: count, dtype: int64

======================================================================
Degree
----------------------------------------------------------------------
Degree
'Class 12'    6080
B.Ed          1867
B.Com         1506
B.Arch        1478
BCA           1433
MSc           1190
B.Tech        1152
MCA           1044
M.Tech        1022
BHM            925
BSc            888
M.Ed           821
B.Pharm        810
M.Com          734
MBBS           696
BBA            696
LLB            671
BE             613
BA             600
M.Pharm        582
MD             572
MBA            562
MA             544
PhD            522
LLM            482
MHM            191
ME             185
Others          35
Name: count, dtype: int64

======================================================================
Have you ever had suicidal thoughts ?
----------------------------------------------------------------------
Have you ever had suicidal thoughts ?
Yes    17656
No     10245
Name: count, dtype: int64

======================================================================
Work/Study Hours
----------------------------------------------------------------------
Work/Study Hours
10    4234
12    3172
11    2892
8     2509
6     2247
9     2026
7     2001
0     1700
4     1614
2     1590
3     1470
5     1296
1     1150
Name: count, dtype: int64

======================================================================
Financial Stress
----------------------------------------------------------------------
Financial Stress
5    6715
4    5775
3    5226
1    5121
2    5061
?       3
Name: count, dtype: int64

======================================================================
Family History of Mental Illness
----------------------------------------------------------------------
Family History of Mental Illness
No     14398
Yes    13503
Name: count, dtype: int64

======================================================================
Depression
----------------------------------------------------------------------
Depression
1    16336
0    11565
Name: count, dtype: int64

In [87]:
categorical_columns = df.select_dtypes(include="object").columns.tolist()

numerical_columns = df.select_dtypes(exclude="object").columns.tolist()

print("Categorical Columns")
print(categorical_columns)

print()

print("Numerical Columns")
print(numerical_columns)

Categorical Columns
['Gender', 'City', 'Profession', 'Sleep Duration', 'Dietary Habits', 'Degree', 'Have you ever had suicidal thoughts ?', 'Financial Stress', 'Family History of Mental Illness']

Numerical Columns
['id', 'Age', 'Academic Pressure', 'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction', 'Work/Study Hours', 'Depression']

Removal of UNnecessary Columns

In [88]:
clean_df = df.copy()

columns_to_remove = [
    "id",
    "City",
    "Profession",
    "Work Pressure",
    "Job Satisfaction"
]

clean_df.drop(columns=columns_to_remove, inplace=True)

In [89]:
clean_df

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,33,5,8.97,2,'5-6 hours',Healthy,B.Pharm,Yes,3,1,No,1
1,Female,24,2,5.90,5,'5-6 hours',Moderate,BSc,No,3,2,Yes,0
2,Male,31,3,7.03,5,'Less than 5 hours',Healthy,BA,No,9,1,Yes,0
3,Female,28,3,5.59,2,'7-8 hours',Moderate,BCA,Yes,4,5,Yes,1
4,Female,25,4,8.13,3,'5-6 hours',Moderate,M.Tech,Yes,1,1,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,Female,27,5,5.75,5,'5-6 hours',Unhealthy,'Class 12',Yes,7,1,Yes,0
27897,Male,27,2,9.40,3,'Less than 5 hours',Healthy,MSc,No,0,3,Yes,0
27898,Male,31,3,6.61,4,'5-6 hours',Unhealthy,MD,No,12,2,No,0
27899,Female,18,5,6.88,2,'Less than 5 hours',Healthy,'Class 12',Yes,10,5,No,1
27900,Male,27,4,9.24,1,'Less than 5 hours',Healthy,BCA,Yes,2,3,Yes,1

In [90]:
clean_df[clean_df["Financial Stress"] == "?"]

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
4458,Female,32,3,5.64,1,'5-6 hours',Healthy,BCA,No,12,?,No,1
13596,Male,29,2,8.94,3,'Less than 5 hours',Unhealthy,B.Ed,No,12,?,Yes,0
19266,Female,20,1,6.83,1,'5-6 hours',Healthy,MBBS,No,9,?,Yes,0

In [91]:
clean_df["Financial Stress"] = clean_df["Financial Stress"].replace("?", np.nan)

clean_df = clean_df.dropna(subset=["Financial Stress"])

clean_df["Financial Stress"] = clean_df["Financial Stress"].astype(int)

In [92]:
clean_df[clean_df["Academic Pressure"] == 0]

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
3501,Female,20,0,5.55,0,'5-6 hours',Moderate,'Class 12',No,0,3,Yes,0
4365,Male,38,0,0.00,0,'5-6 hours',Healthy,'Class 12',No,2,3,No,0
13909,Female,20,0,0.00,0,'Less than 5 hours',Moderate,'Class 12',Yes,12,3,Yes,1
14855,Male,21,0,0.00,0,'7-8 hours',Moderate,'Class 12',Yes,3,3,Yes,0
20913,Male,18,0,0.00,0,'Less than 5 hours',Moderate,'Class 12',Yes,9,5,No,1
24417,Female,30,0,5.47,2,'Less than 5 hours',Unhealthy,B.Com,Yes,5,1,No,0
25746,Male,18,0,0.00,0,'7-8 hours',Moderate,'Class 12',Yes,9,4,No,1
26719,Female,24,0,0.00,0,'More than 8 hours',Unhealthy,'Class 12',No,0,5,No,0
27178,Male,36,0,8.54,3,'More than 8 hours',Moderate,'Class 12',Yes,8,5,Yes,1

In [93]:
print("Rows with Academic Pressure = 0:",
      (clean_df["Academic Pressure"] == 0).sum())

Rows with Academic Pressure = 0: 9

In [94]:
clean_df = clean_df[clean_df["Academic Pressure"] != 0]

In [95]:
clean_df["Academic Pressure"].value_counts().sort_index()

Academic Pressure
1    4800
2    4177
3    7461
4    5155
5    6296
Name: count, dtype: int64

### Cleaning Step – Academic Pressure

The survey uses a Likert scale from **1 to 5** for Academic Pressure.

Nine records contained a value of **0**, which falls outside the valid range and is considered an invalid response.

These rows were removed from the dataset to maintain data quality.

In [96]:
clean_df[clean_df["Sleep Duration"] == "Others"]

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1963,Female,30,3,5.42,2,Others,Unhealthy,B.Ed,Yes,1,2,No,0
3807,Female,18,3,6.03,4,Others,Unhealthy,BA,Yes,12,5,No,1
3984,Female,27,4,5.08,5,Others,Healthy,M.Tech,Yes,8,5,Yes,1
4535,Female,22,4,6.92,3,Others,Moderate,MCA,Yes,3,3,Yes,1
5526,Female,31,2,7.27,5,Others,Healthy,B.Arch,No,3,1,No,0
5786,Male,23,5,8.52,4,Others,Moderate,BE,Yes,12,4,Yes,1
6740,Male,20,3,6.37,2,Others,Unhealthy,BSc,No,10,1,No,0
7696,Male,31,3,8.21,4,Others,Moderate,BA,No,2,3,No,0
7875,Female,28,4,6.38,5,Others,Moderate,M.Ed,No,8,3,No,0
12933,Male,28,2,7.85,4,Others,Unhealthy,BA,Yes,10,4,No,1
14382,Female,33,4,7.87,4,Others,Moderate,PhD,No,10,2,Yes,0
14988,Male,26,2,7.11,4,Others,Unhealthy,PhD,Yes,9,2,No,0
15103,Male,25,3,9.84,1,Others,Unhealthy,BE,Yes,4,1,Yes,1
15958,Male,23,2,9.60,1,Others,Unhealthy,B.Arch,Yes,1,1,Yes,0
18224,Female,31,2,9.24,1,Others,Moderate,MBA,Yes,12,5,No,1
20315,Male,32,4,9.39,2,Others,Healthy,M.Tech,No,4,3,Yes,1
22903,Male,34,3,5.66,4,Others,Moderate,MSc,No,12,1,No,0
25204,Female,30,4,9.96,1,Others,Unhealthy,B.Com,Yes,1,2,Yes,1

In [97]:
clean_df = clean_df[clean_df["Sleep Duration"] != "Others"]

In [98]:
clean_df[clean_df["Dietary Habits"] == "Others"]

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
5684,Male,23,3,9.98,5,'Less than 5 hours',Others,B.Com,Yes,4,5,No,1
6892,Male,18,1,6.05,5,'7-8 hours',Others,'Class 12',No,4,4,No,0
8263,Female,21,2,7.28,4,'Less than 5 hours',Others,B.Pharm,Yes,0,3,Yes,0
8456,Female,32,4,9.54,4,'5-6 hours',Others,B.Ed,Yes,4,2,No,1
11746,Male,34,5,9.04,1,'More than 8 hours',Others,B.Tech,Yes,4,5,Yes,1
12763,Female,23,2,6.91,5,'5-6 hours',Others,M.Pharm,No,6,3,No,1
13758,Male,34,5,8.24,5,'5-6 hours',Others,MCA,Yes,11,1,Yes,1
14504,Male,26,1,7.49,2,'Less than 5 hours',Others,LLB,Yes,6,4,No,0
15087,Female,27,5,5.82,3,'Less than 5 hours',Others,BSc,Yes,7,1,No,1
22515,Male,30,5,5.99,2,'7-8 hours',Others,M.Ed,Yes,7,4,No,1
23506,Male,24,1,8.47,2,'7-8 hours',Others,MCA,Yes,0,5,No,1
26061,Male,25,3,5.60,3,'Less than 5 hours',Others,BCA,Yes,2,1,No,0

In [99]:
clean_df = clean_df[clean_df["Dietary Habits"] != "Others"]

In [100]:
clean_df[clean_df["Age"] > 35]

,Gender,Age,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
201,Female,39,5,6.51,4,'7-8 hours',Moderate,M.Tech,Yes,7,2,No,1
1076,Female,42,2,9.03,5,'More than 8 hours',Moderate,'Class 12',Yes,3,1,Yes,0
1330,Male,36,5,7.10,5,'Less than 5 hours',Moderate,MSc,Yes,0,2,Yes,0
2885,Female,36,3,5.90,5,'7-8 hours',Healthy,MCA,No,11,5,Yes,0
2909,Female,58,4,8.58,1,'7-8 hours',Healthy,'Class 12',No,4,4,No,0
3337,Female,39,4,5.60,2,'Less than 5 hours',Unhealthy,M.Ed,Yes,9,5,Yes,1
3436,Male,49,3,6.47,3,'5-6 hours',Moderate,'Class 12',Yes,2,1,Yes,0
4386,Female,51,2,8.26,3,'Less than 5 hours',Moderate,MBBS,Yes,5,5,Yes,0
5370,Male,36,1,5.61,3,'More than 8 hours',Unhealthy,B.Com,No,7,2,No,0
5537,Female,44,1,6.83,3,'Less than 5 hours',Unhealthy,BSc,No,4,3,No,0
6576,Male,38,2,6.02,5,'More than 8 hours',Moderate,B.Arch,No,5,2,No,0
6662,Male,43,5,5.64,2,'5-6 hours',Moderate,B.Ed,No,9,4,Yes,1
8819,Male,38,5,5.74,1,'5-6 hours',Healthy,MBBS,No,8,3,Yes,1
9006,Male,46,1,6.10,3,'7-8 hours',Unhealthy,PhD,No,4,2,No,0
9044,Female,38,5,5.11,4,'Less than 5 hours',Healthy,BSc,Yes,10,1,Yes,1
9238,Male,59,1,8.14,1,'5-6 hours',Unhealthy,PhD,Yes,10,4,Yes,0
11532,Male,42,5,6.10,1,'Less than 5 hours',Healthy,MBBS,Yes,10,4,No,1
12351,Female,36,1,9.63,5,'5-6 hours',Moderate,B.Com,No,0,4,Yes,0
13499,Male,54,5,9.60,2,'More than 8 hours',Unhealthy,B.Ed,Yes,9,3,Yes,0
13618,Female,48,3,7.48,5,'More than 8 hours',Healthy,LLB,No,2,4,No,0
14739,Female,38,1,9.49,3,'5-6 hours',Moderate,'Class 12',No,9,4,No,0
14819,Female,56,3,7.94,5,'5-6 hours',Unhealthy,BSc,No,1,5,Yes,0
16757,Female,43,5,9.67,1,'7-8 hours',Healthy,MSc,Yes,2,3,Yes,0
17917,Female,37,1,9.41,3,'5-6 hours',Moderate,BHM,No,0,4,Yes,0
18230,Female,39,5,5.60,5,'More than 8 hours',Healthy,M.Ed,No,2,5,No,0
18766,Female,46,3,6.83,1,'5-6 hours',Healthy,MCA,No,8,5,No,1
20097,Male,37,1,5.41,1,'5-6 hours',Unhealthy,BSc,Yes,1,5,Yes,0
20373,Female,36,1,7.10,3,'More than 8 hours',Unhealthy,ME,No,6,1,Yes,0
20493,Female,38,1,9.96,4,'5-6 hours',Moderate,M.Com,Yes,9,3,No,0
22101,Female,42,5,9.56,2,'5-6 hours',Moderate,PhD,No,4,2,Yes,0
22710,Female,36,3,8.35,3,'5-6 hours',Healthy,'Class 12',No,5,4,Yes,0
22859,Male,38,3,8.94,2,'7-8 hours',Healthy,M.Pharm,Yes,0,2,No,0
23414,Male,42,5,5.32,4,'7-8 hours',Unhealthy,'Class 12',No,12,5,Yes,1
25202,Female,48,3,5.32,4,'7-8 hours',Unhealthy,'Class 12',No,1,4,Yes,1
25705,Male,38,2,7.71,1,'5-6 hours',Moderate,MBBS,No,2,5,Yes,0
25974,Male,41,3,5.85,1,'5-6 hours',Moderate,'Class 12',No,11,5,Yes,1
27334,Female,48,1,8.92,4,'7-8 hours',Moderate,MD,Yes,12,4,Yes,0

In [101]:
clean_df = clean_df[clean_df["Age"] < 35]

In [102]:
clean_df["Depression"].value_counts()

Depression
1    16302
0    11510
Name: count, dtype: int64

In [103]:
clean_df["Depression"].value_counts(normalize=True) * 100

Depression
1    58.614986
0    41.385014
Name: proportion, dtype: float64

In [107]:
output_path = r"D:\Project\Mental-Health-Analyzer-New\ml\data\processed\cleaned_kaggle.csv"

clean_df.to_csv(output_path, index=False)

print("✅ Dataset saved successfully!")

✅ Dataset saved successfully!

## Summary of Data Cleaning

### Key Cleaning Operations
- Removed non-informative columns (`id`, `City`, `Profession`, `Work Pressure`, `Job Satisfaction`).
- Removed invalid responses in `Financial Stress`.
- Removed invalid values in `Academic Pressure` and `Study Satisfaction`.
- Removed ambiguous `Others` responses from `Sleep Duration` and `Dietary Habits`.
- Removed inconsistent age records.

### Outcome
The cleaned dataset is ready for EDA, feature engineering, predictive modeling, and the wellness score framework.